### ISSUE TITLE
xsiSchemaLocation in generated XML documents not processable by AASXPackageExplorer

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-aas4j/aas4j#186] opened 2023-10-19 22:49 UTC
Hi,

I am currently trying to import AAS files in xml format generated by the AAS4j library into the [AASXPackageExplorer](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-09-12.alpha), however it seems the editor cannot handle the xsi:schemaLocation produced by AAS4j.

The generated version contains a black before the file name 
```
<aas:environment xmlns:aas="https://admin-shell.io/aas/3/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://admin-shell.io/aas/3/0 AAS.xsd">
```
However, the Editor loads the file, if it is provided as
```
<aas:environment xmlns:aas="https://admin-shell.io/aas/3/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://admin-shell.io/aas/3/0/AAS.xsd">
```

Expected behavior:
The generated XML file is imported into the AASXPackageExplorer.

**Comment by twebermartins** [comment] 2023-11-03 07:57
Thanks @bs-jokri for raising this. We will have a look at it.

**Comment by FrankSchnicke** [comment] 2023-11-06 09:57
I'm not sure if this is a bug related to AAS4J. In the [schema location](https://www.w3.org/TR/xmlschema-1/#schema-loc), pairs of namespaces as well as their respective schema location are provided. Thus, _xsi:schemaLocation="https://admin-shell.io/aas/3/0/AAS.xsd"_ does not make much sense due to the file itself missing (i.e., the second entry in the schemaLocation tag). Nevertheless, it would make more sense to replace _AAS.xsd_ with _https://github.com/admin-shell-io/aas-specs/blob/V3.0.7/schemas/xml/AAS.xsd_

Can you provide an error log of the AASX Package Explorer of an unsuccessful load?

**Comment by sebbader-sap** [comment] 2023-11-09 10:43
I was not able to reproduce the described behaviour with AASX Package Explorer v2023-09-12.

However, what I did find out:

1. This minimal example can be loaded by the Package Explorer:
```
<?xml version='1.0' encoding='UTF-8'?>
<aas:environment xmlns:aas="https://admin-shell.io/aas/3/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://admin-shell.io/aas/3/0 AAS.xsd">
  <aas:assetAdministrationShells>
    <aas:assetAdministrationShell>
      <aas:id>AssetAdministrationShell---2CEBD072</aas:id>
      <aas:assetInformation>
        <aas:assetKind>Instance</aas:assetKind>
      </aas:assetInformation>
    </aas:assetAdministrationShell>
  </aas:assetAdministrationShells>
  <aas:submodels />
  <aas:conceptDescriptions />
</aas:environment>
```

2. AAS4J serialises this here (note the missing aas:submodels and aas:conceptDescriptions):
```
<?xml version='1.0' encoding='UTF-8'?>
<aas:environment xmlns:aas="https://admin-shell.io/aas/3/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://admin-shell.io/aas/3/0 AAS.xsd">
  <aas:assetAdministrationShells>
    <aas:assetAdministrationShell>
      <aas:id>AssetAdministrationShell---2CEBD072</aas:id>
      <aas:assetInformation>
        <aas:assetKind>Instance</aas:assetKind>
      </aas:assetInformation>
    </aas:assetAdministrationShell>
  </aas:assetAdministrationShells>
</aas:environment>
```

**Comment by sebbader-sap** [comment] 2023-11-09 10:46
As https://github.com/admin-shell-io/aas-specs/blob/2fe82a66ca502f9c5aea1ef0de0baaa729469faf/schemas/xml/AAS.xsd#L327 states that, e.g., `submodels` is optional but must not be empty, I see this as a bug in the Package Explorer.

**Comment by sebbader-sap** [comment] 2023-11-09 10:46
@FrankSchnicke can you follow my arguments? If so, can you add it to the bug you have already opened in the Package Explorer?

**Comment by sebbader-sap** [comment] 2023-11-09 10:50
(Remark: I had only a limited environment available for my tests, I was able to use v2023-09-12 but without needed .NET Core libraries - no permissions to install on my VM. Therefore, I am not 100% sure whether my Package Explorer behaves identical to others.)

**Comment by FrankSchnicke** [comment] 2023-11-10 06:17
@sebbader-sap I added your findings to the ticket over at the AASX PE Repo: https://github.com/admin-shell-io/aasx-package-explorer/issues/653.

@bs-jokri since @sebbader-sap could not reproduce the issue, I will close this ticket. For the general overview of compatibility issues related to bugs with AAS4J but also with AASX PE see https://github.com/eclipse-aas4j/aas4j/issues/158

**Closed by FrankSchnicke** 2023-11-10 06:17 UTC

**Comment by bs-jokri** [comment] 2023-11-10 15:12
@sebbader-sap @FrankSchnicke thanks to both of you looking into the issue. I also tested again and can second @sebbader-sap observations. My test model also missed some optional elements, which might caused the problem not the schemaLocation. Thus, fine with me closing the issue
